# Generated by Django 4.2.27 on 2026-01-27 18:22

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('RELIGIOUS', 'Religious Ceremony'), ('CONCERT', 'Concert/Entertainment'), ('MARKET', 'Market/Food Festival'), ('COMMUNITY', 'Community Gathering')], max_length=20)),
                ('description', models.TextField()),
                ('banner_image', models.URLField(blank=True)),
                ('design_template_external_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('TEMPLE', 'Temple'), ('MARKET', 'Thai Grocery/Market'), ('RESTAURANT', 'Restaurant'), ('PARTNER', 'Partner Venue')], default='TEMPLE', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('website', models.URLField(blank=True, null=True)),
                ('country_code', models.CharField(help_text='e.g. DE, FR, SE', max_length=2)),
                ('related_store_external_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_city', models.CharField(max_length=100)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('saved_events', models.ManyToManyField(blank=True, related_name='interested_members', to='society.event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='somtam_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='society.location'),
        ),
    ]
