# Generated by Django 4.2.27 on 2026-02-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_external_id',
            field=models.CharField(db_index=True, default=1, max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
