# Generated by Django 4.2.27 on 2026-02-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_event_event_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_thai',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='sub_title_thai',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
