# Generated by Django 4.2.27 on 2026-02-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_event_description_thai_event_sub_title_thai'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_info',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('WEBSITE', 'Website')], default='EMAIL', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='event_website',
            field=models.URLField(blank=True, default='www.somtamevent.com'),
        ),
        migrations.AddField(
            model_name='event',
            name='hightlight',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='hightlight_thai',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
