# Generated by Django 4.2.27 on 2026-02-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0004_event_contact_info_event_event_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('TEMPLE', 'Temple Day Tracker'), ('MARKET', 'Market/Food Festival'), ('EXHIBITION', 'Music/Exhibition Venue'), ('PARTNER', 'Partner Venue')], default='TEMPLE', max_length=20),
        ),
    ]
